---
# This ZTP has dependency on a management cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

commonLabels:
  telco-gitops/ztp: combined-ran

resources:
  - 01-agent-ran1-pool5-roskosb-info.yaml
  - 01-cluster-ran1-pool5-roskosb-info.yaml
  - 01-infraenv-ran1-pool5-roskosb-info.yaml
  - 01-nmstate-ran1-skylark-vm-cars-lab.yaml
# - 02-bmh-ran1-pool5-roskosb-info-RWN-VMCTRLPLANE.yaml
