---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: mgmt-pool5-roskosb-info
 namespace: telco-gitops
spec:
  generators:
    - git:
        directories:
          - path: mgmt.pool5.roskosb.info/config-*
        repoURL: 'https://github.com/broskos/pool5-gitops'
        revision: HEAD
  template:
    metadata:
      name: '00-mgmt-{{path.basename}}'
      namespace: telco-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/broskos/pool5-gitops'
        targetRevision: HEAD