---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super1-ran1-pool5-roskosb-info
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: cG9vbDVkcmFj
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super2-ran1-pool5-roskosb-info
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: cG9vbDVkcmFj
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super3-ran1-pool5-roskosb-info
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: cG9vbDVkcmFj
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker1-ran1-pool5-roskosb-in
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: cG9vbDVkcmFj
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker1-ran1-pool5-roskosb-in
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: cG9vbDVkcmFj
type: Opaque
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: bmc-du1-fec2-ran1-roskosb-in
#  namespace: assisted-installer
#data:
#  username: cm9vdA==
#  password: YWx0aW9zdGFyITIz
#type: Opaque
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: bmc-du1-ldc1-ran1-roskosb-in
#  namespace: assisted-installer
#data:
#  username: cm9vdA==
#  password: YWx0aW9zdGFyITIz
#type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super1-ran1-pool5-roskosb-info
  namespace: assisted-installer
  labels:
    # InfraEnv to use
    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
    #bmac.agent-install.openshift.io/installer-args: '["--append-karg", "bond=bond0:ens7f0,ens7f1:mode=active-backup ip=bond0:dhcp", "--save-partindex", "1", "--copy-network"]'
    # https://github.com/openshift/assisted-service/blob/master/docs/Kube-API.md
    #bmac.agent-install.openshift.io/installer-args: '["--append-karg", "ip=192.0.2.2::192.0.2.254:255.255.255.0:core0.example.com:enp1s0:none", "--save-partindex", "1", "--copy-network"]'
    #bmac.agent-install.openshift.io/ignition-config-overrides: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/tmp/example", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
spec:
  online: true
  bootMACAddress: E4:43:4B:4E:40:2D
  automatedCleaningMode: disabled
  bmc:
    # https://github.com/metal3-io/baremetal-operator/blob/master/docs/api.md
    address: idrac-virtualmedia://10.1.177.51/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-super1-ran1-pool5-roskosb-info
    disableCertificateVerification: True

# oc delete -f 02-bmh-ran1-pool5-roskosb-info.yaml ; sleep 3 ; oc create -f 02-bmh-ran1-pool5-roskosb-info.yaml
# watch -c "oc get bmh pool5-ran1-pool5-roskosb-info -o jsonpath='{.status}' | jq . "
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super2-ran1-pool5-roskosb-info
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: E4:43:4B:4E:3F:B9
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://10.1.177.52/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-super2-ran1-pool5-roskosb-info
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super3-ran1-pool5-roskosb-info
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: E4:43:4B:56:8B:D1
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://10.1.177.53/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-super3-ran1-pool5-roskosb-info
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker1-ran1-pool5-roskosb-in
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: worker
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
    #bmac.agent-install.openshift.io/installer-args: '["--append-karg", "bond=bond0:ens7f0,ens7f1:mode=active-backup ip=10.50.0.152::10.50.0.1:255.255.255.0:cu2.ran1.pool5.roskosb.info:bond0:none", "--append-karg", "ip=ens1f0:off", "--append-karg", "ip=ens1f1:off", "--append-karg", "nameserver=10.40.0.100", "--copy-network"]'
spec:
  online: true
  bootMACAddress: E4:43:4B:56:89:B9
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://10.1.177.54/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-worker1-ran1-pool5-roskosb-in
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker2-ran1-pool5-roskosb-in
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: worker
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
#    bmac.agent-install.openshift.io/installer-args: '["--append-karg", "bond=bond0:ens7f0,ens7f1:mode=active-backup ip=bond0:dhcp", "--copy-network"]'
#    bmac.agent-install.openshift.io/ignition-config-overrides: ''
spec:
  online: true
  bootMACAddress: E4:43:4B:4E:44:B1
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://10.1.177.55/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-worker2-ran1-pool5-roskosb-in
    disableCertificateVerification: True
#---
#apiVersion: metal3.io/v1alpha1
#kind: BareMetalHost
#metadata:
#  name: du1-fec2-ran1-roskosb-in
#  namespace: assisted-installer
#  labels:
#    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
#  annotations:
#    inspect.metal3.io: disabled
#    bmac.agent-install.openshift.io/role: worker
#    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
#spec:
#  online: true
#  bootMACAddress: ac:1f:6b:e1:79:ba
#  automatedCleaningMode: disabled
#  bmc:
#    address: idrac-virtualmedia://172.28.11.40/redfish/v1/Systems/System.Embedded.1
#    credentialsName: bmc-du1-fec2-ran1-roskosb-in
#    disableCertificateVerification: True
#---
#apiVersion: metal3.io/v1alpha1
#kind: BareMetalHost
#metadata:
#  name: du1-ldc1-ran1-roskosb-in
#  namespace: assisted-installer
#  labels:
#    infraenvs.agent-install.openshift.io: "infraenv-ran1-pool5-roskosb-info"
#  annotations:
#    inspect.metal3.io: disabled
#    bmac.agent-install.openshift.io/role: worker
#    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
#spec:
#  online: true
#  bootMACAddress: 3c:ec:ef:30:52:64
#  automatedCleaningMode: disabled
#  bmc:
#    address: idrac-virtualmedia://172.28.11.42/redfish/v1/Systems/System.Embedded.1
#    credentialsName: bmc-du1-ldc1-ran1-roskosb-in
#    disableCertificateVerification: True
